# Copyright (c) 2025, b»robotized
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Source of this file is https://github.com/b-robotized/ros_team_workspace repository.
# Template authors: Nikola Banovic, Daniel Azanov, Dr. Denis
#

/**:
  ros__parameters:
    robot_description_planning:
      # joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

      # For beginners, we downscale velocity and acceleration limits.
      # You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
      default_velocity_scaling_factor: 0.1
      default_acceleration_scaling_factor: 0.1

      # Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
      # Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
      joint_limits:
        joint_1:
          # has_position_limits: true
          # min_position: -0.681  # min: <enter the values for the robot>
          # max_position: 3.5     # max:  <enter the values for the robot>
          has_velocity_limits: true
          max_velocity: 1.7453292519943295    # max: <enter the values for the robot>
          has_acceleration_limits: true
          max_acceleration: 7.0
          has_deceleration_limits: true
          max_deceleration: -7.0
        joint_2:
          # has_position_limits: true
          # min_position: -1.57  # min: <enter the values for the robot>
          # max_position: 1.57   # max:  <enter the values for the robot>
          has_velocity_limits: true
          max_velocity: 1.5707963267948966   # max: <enter the values for the robot>
          has_acceleration_limits: true
          max_acceleration: 10.0
          has_deceleration_limits: true
          max_deceleration: -10.0
        joint_3:
          # has_position_limits: true
          # min_position: 0.1      # min: -158°: -2,757620218151041 rad
          # max_position: 2.7053   # max:  158°:  2,757620218151041 rad
          has_velocity_limits: true
          max_velocity: 1.5707963267948966   # max: <enter the values for the robot>
          has_acceleration_limits: true
          max_acceleration: 10.0
          has_deceleration_limits: true
          max_deceleration: -10.0
        joint_4:
          # has_position_limits: true
          # min_position: -1.57  # min: <enter the values for the robot>
          # max_position: 1.57   # max:  <enter the values for the robot>
          has_velocity_limits: true
          max_velocity: 2.9670597283903604  # max: <enter the values for the robot>
          has_acceleration_limits: true
          max_acceleration: 15.0
          has_deceleration_limits: true
          max_deceleration: -15.0
        joint_5:
          # has_position_limits: true
          # min_position: 0.0    # min: <enter the values for the robot>
          # max_position: 3.14   # max:  <enter the values for the robot>
          has_velocity_limits: true
          max_velocity: 2.0943951023931953  # max: <enter the values for the robot>
          has_acceleration_limits: true
          max_acceleration: 15.0
          has_deceleration_limits: true
          max_deceleration: -15.0
        joint_6:
          # has_position_limits: true
          # min_position: 0.0   # min: <enter the values for the robot>
          # max_position: 6.183  # max:  <enter the values for the robot>
          has_velocity_limits: true
          max_velocity: 3.3161255787892263  # max: <enter the values for the robot>
          has_acceleration_limits: true
          max_acceleration:  20.0
          has_deceleration_limits: true
          max_deceleration: -20.0
